import { Innovator } from '@/types/innovator';

export const innovatorsData: Innovator[] = [
  {
    id: '1',
    name: 'Kevin Webb',
    image: '/trusted-by-innovators/Kevin-Webb.png',
    company: 'KW Fitness',
    position: 'Founder',
    testimonialTitle: "Ideas to Reality",
    testimonialText: 'Working with Brillarix on PT Metrics was exceptional. They transformed my vision into a clean, powerful platform with flawless execution and communication. Their partnership and creative problem-solving helped build a product that will truly elevate our business.',
    companyLogo: '/client-logos/KW.png',
  },
  {
    id: '2',
    name: 'Kapil Meena',
    image: '/trusted-by-innovators/Kapil-Meena.png',
    company: 'Visionary Clouds',
    position: 'Founder',
    testimonialTitle: 'Website Transformation',
    testimonialText: "BRILLARIX built a stunning, high-performing website that exceeded my expectations. The team understood exactly what I needed and delivered flawless design and functionality. I’ve already seen a strong boost in engagement and conversions.",
    companyLogo: '/client-logos/VisionaryClouds.png',
  },
  {
    id: '3',
    name: 'Daniel S.',
    image: '',
    company: 'Signm',
    position: 'CEO',
    testimonialTitle: 'Exceptional Service',
    testimonialText: 'I’ve worked with Brillarix for several years on the build and ongoing development of my company, SIGNM. They delivered full-stack development, custom APIs, and a stable GCP + MongoDB infrastructure supporting millions of daily events. Over 4,000 users have since engaged with the platform — a testament to the system’s robustness.',
    companyLogo: '/client-logos/Signm.png',
  },
  {
    id: '4',
    name: 'Angie Schwab',
    image: '/trusted-by-innovators/Angela-Schwab.png',
    company: 'Trialynx',
    position: 'CEO',
    testimonialTitle: 'Empowered Efficiency',
    testimonialText: 'Brillarix turned our concept into a fully operational business with repeat customers in under a year. We expanded to four countries and boosted medical writing speed by 90%. Their platform has enabled us to launch more than 50 clinical trials.',
    companyLogo: '/client-logos/Trialynx.png',
  },
  {
    id: '5',
    name: 'Evan Lindsay',
    image: '/trusted-by-innovators/Evan-Lindsay.png',
    company: 'Gym Builder',
    position: 'Founder',
    testimonialTitle: 'Visibility Boost',
    testimonialText: 'The platform built by Brillarix has been a game-changer for our visibility. We can isolate issues in minutes, and gyms using it consistently see 8–10%+ jumps in conversions. It’s strengthened our operations, boosted retention, and helped us deliver better client results.',
    companyLogo: '/client-logos/GymBuilder.png',
  },
];

