import { Innovator } from '@/types/innovator';

export const innovatorsData: Innovator[] = [
  {
    id: '1',
    name: 'Kevin Webb',
    image: '/trusted-by-innovators/Kevin-Webb.png',
    company: 'KW Fitness',
    position: 'Founder',
    testimonialTitle: "Ideas to Reality",
    testimonialText: 'Working with Brillarix on PT Metrics was exceptional. They transformed my vision into a clean, powerful platform with flawless execution and communication. Their partnership and creative problem-solving helped build a product that will truly elevate our business.',
    companyLogo: '/client-logos/KW.png',
    filter: false,
  },
  {
    id: '2',
    name: 'Kapil Meena',
    image: '/trusted-by-innovators/Kapil-Meena.png',
    company: 'Visionary Clouds',
    position: 'Founder',
    testimonialTitle: 'Website Transformation',
    testimonialText: "BRILLARIX built a stunning, high-performing website that exceeded my expectations. The team understood exactly what I needed and delivered flawless design and functionality. I’ve already seen a strong boost in engagement and conversions.",
    companyLogo: '/client-logos/VisionaryClouds.png',
    filter: true,
  },
  {
    id: '3',
    name: 'Daniel S.',
    image: '',
    company: 'Signm',
    position: 'CEO',
    testimonialTitle: 'Exceptional Service',
    testimonialText: 'I’ve worked with Brillarix for several years on the build and ongoing development of my company, SIGNM. They delivered full-stack development, custom APIs, and a stable GCP + MongoDB infrastructure supporting millions of daily events. Over 4,000 users have since engaged with the platform, a testament to the system’s robustness.',
    companyLogo: '/client-logos/Signm.png',
    filter: true,
  },
  {
    id: '4',
    name: 'Angie Schwab',
    image: '/trusted-by-innovators/Angela-Schwab.png',
    company: 'Trialynx',
    position: 'CEO',
    testimonialTitle: 'Empowered Efficiency',
    testimonialText: 'In under a year, Brillarix helped us transform our initial concept into a fully operational business with a recurring client base. Their platform was the catalyst for our expansion into four countries, accelerating our medical writing speed by 90% and enabling the launch of over 50 clinical trials.',
    companyLogo: '/client-logos/Trialynx.png',
    filter: true,
  },
  {
    id: '5',
    name: 'Evan Lindsay',
    image: '/trusted-by-innovators/Evan-Lindsay.png',
    company: 'Gym Builder',
    position: 'Founder',
    testimonialTitle: 'Visibility Boost',
    testimonialText: 'The platform built by Brillarix has been a game-changer for our visibility. We can isolate issues in minutes, and gyms using it consistently see 8–10%+ jumps in conversions. It’s strengthened our operations, boosted retention, and helped us deliver better client results.',
    companyLogo: '/client-logos/GymBuilder.png',
    filter: true,
  },
  {
    id: '6',
    name: 'Kevin Mills',
    image: '/trusted-by-innovators/Kevin-Mills.png',
    company: 'Streamlined Media',
    position: 'Founder',
    testimonialTitle: 'Simplifying Complex Processes',
    testimonialText: 'Our experience with Brillarix was exceptional. They adeptly facilitated the development of several intricate internal processes for our company, all while leveraging no-code technology to ensure accessibility and usability across our entire team.',
    companyLogo: '/client-logos/Streamlined.png',
    filter: false,
  },
  {
    id: '7',
    name: 'Jeff Gottschalk',
    image: '',
    company: 'Cleeri',
    position: 'Founder',
    testimonialTitle: 'Simplifying Complex Processes',
    testimonialText: 'Brillarix has been an integral partner in our product development journey. Their clear communication and attention to detail set them apart. From low-code foundations to a full-stack transition, their versatility, consistency, and empathy made the process seamless. We highly recommend the Brillarix team.',
    companyLogo: '/client-logos/Cleeri.png',
    filter: true,
  },
];

